apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source-repo
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/remkohdev/spring-boot-app